### ISSUE TITLE
Llmfoo not usable in Colab

### ISSUE THREAD

**Issue by bigr00** [robocorp/llmfoo#1]
Hi. Thanks for the awesome library!

For typical use cases, I’m using Colab to code and execute Gradio apps. I’d love to use Lllmfoo, but have to update the python version to 3.11 and then pip etc, making it a 5-6 minute execution just to use the library. 

If at all possible, making a downgraded requirement will enable for the library to be just installed in one command, as opposed to 10 or so.

![IMG_0276](https://github.com/robocorp/llmfoo/assets/28863322/55abc1e1-0ceb-4edb-8652-9a0b3f006512)

![IMG_0277](https://github.com/robocorp/llmfoo/assets/28863322/35c63a0f-efa2-4d05-9c34-9f37554636d5)

**Comment by mkorpela** [comment]
@bigr00 thanks for the report!

**Comment by mkorpela** [comment]
Version 0.5.0 released with 3.10 supported.
